# Generated by Django 3.2.11 on 2022-01-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220119_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pud_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
